module.exports.token = "Your TOKEN HERE"
module.exports.prefix = "YOUR PREFIX HERE"
module.exports.yt = "YOUR YOUTUBE API KEY HERE"
module.exports.color = "#4287f5", // some embed's color
module.exports.playmsg = ['`%song%` 큐!', '`%song%` 한곡 뽑아볼게', '%song% 재생!', '%song% 시작!']
module.exports.owner = [""]
module.exports.koreanbotsToken = ""
module.exports.displayname = "BOT's NAME"
module.exports.DBUser = ""
module.exports.DBPassword = ""
module.exports.DBName = ""